// Hand-resolved from litert/build_common/build_config.h.in (google-ai-edge/LiteRT) -- normally
// generated by LiteRT's own CMake configure step, which we don't run since we link against the
// prebuilt libLiteRt.so shipped via the app's litert:2.2.0 Gradle dependency rather than
// building LiteRT from source. Neither GPU nor NPU support is disabled: NpuUnetEngine's whole
// purpose is running on the NPU, and the prebuilt .so we link against was built with NPU support
// (see libLiteRtDispatch_GoogleTensor.so + the litert-sdk-google-tensor gated SDK already used
// to AOT-compile every UNet piece this loads).
#ifndef LITERT_BUILD_COMMON_BUILD_CONFIG_H_
#define LITERT_BUILD_COMMON_BUILD_CONFIG_H_

// (Neither LITERT_DISABLE_GPU nor LITERT_DISABLE_NPU defined -- both features stay enabled.)

#endif  // LITERT_BUILD_COMMON_BUILD_CONFIG_H_
